language: cpp
compiler:
#  - clang
  - gcc
addons:
  apt:
    packages:
      - libfuse-dev
      - libcurl4-nss-dev
      - libcrypto++-dev
script: ./switch_build.sh server && autoreconf --install && ./configure --with-mountvhd && make && ./switch_build.sh client && autoreconf --install && ./configure --enable-headless && make